name: Build socat binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build socat in Docker
        run: |
          docker build -t socat-builder -f Dockerfile .

      - name: Extract socat binary from image
        run: |
          container_id=$(docker create socat-builder)
          docker cp "$container_id":/socat-1.7.4.4/socat ./socat
          docker rm "$container_id"
          chmod +x socat

    #   - name: Upload socat binary as artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: socat-binary
    #       path: ./socat

      - name: Upload socat to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Socat Binary (Latest)
          files: ./socat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
